function cols=selectCustomizedMarkers(MarkerNames)
		
	markers={'APOAI1' 'CSF1PO' 'D10S1248' 'D10S2325' 'D11S554'  'D12S391' ...
		'D13S317'  'D16S539'  'D17S906'  'D18S51' 'D19S433'  'D1S1656'  ...
		'D21S11' 'D21S2055' 'D22S1045' 'D2S1338'  'D2S1360'  'D2S441' ...
		'D3S1358'  'D3S1744'  'D4S2366'  'D5S2500'  'D5S818' 'D6S474' ...
		'D7S1517'  'D7S820' 'D8S1132'  'D8S1179'  'FGA'  'PENTA\_D'  ...
		'PENTA\_E'  'SE33' 'TH01' 'TPOX' 'VWA' };
	
	mainWindow = figure('Name','Select Markers','NumberTitle','off',...
		'units','normalized',...
		'OuterPosition',[0.01 0.01 0.98 0.29],...
		'MenuBar','none');
	
	
	FreqsPlot=openfig('Frequencies.fig','reuse');
	FreqsPlot.OuterPosition=[0.01 0.3 0.98 0.69];
	figure(FreqsPlot);

		
	
	txtTitle = annotation(mainWindow,'textbox','String',...
		'Please Choose Which Markers to Use...', ...
		'FontSize',20,...
		'units','normalized',...
		'Position', [0 0.7 0.9 0.3],...
		'HorizontalAlignment', 'center',...
		'VerticalAlignment', 'middle',...
		'Interpreter','Tex',...
		'LineStyle','none'); %#ok<*NASGU>
	
	it=1;
	for jj=5:-1:1
		for ii=1:7
			MarkNam(it)=annotation(mainWindow,'textbox',...
				'String',markers{it},...
				'Units','Normalized',...
				'Position',[ 0.04+0.14*(ii-1) 0.1+0.1*(jj-1) 0.1 0.09],...
				'LineStyle','none',...
				'HorizontalAlignment', 'left',...
				'VerticalAlignment', 'baseline');
			NumMark(it)=uicontrol(mainWindow,'Style','checkbox',...
				'Units','Normalized',...
				'Position',[ 0.01+0.14*(ii-1) 0.12+0.1*(jj-1) 0.03 0.09],...
				'Value',0);
			it=it+1;
		end
	end
	
	%Run BUTTON
	buttonRun = uicontrol('Parent', mainWindow,'Style','pushbutton',...
		'Units','normalized',...
		'Position',[0.9 0.8 0.08 0.15],...
		'String','Proceed...',...
		'Callback',@buttonRun_callback);
	
	
	function buttonRun_callback(hObject,eventdata) %#ok<*INUSD>

		marks=zeros(1,numel(NumMark));
		for iter=1:numel(NumMark)
			marks(iter)=get(NumMark(iter),'Value');
		end
		cols=1:35;
		marks_binnary=~~(marks);
		marks=marks-marks_binnary;
		tmp=cols(marks_binnary);
		while any(marks)
			marks_binnary=~~(marks);
			marks=marks-marks_binnary;
			tmp=[tmp cols(marks_binnary)]; %#ok<*AGROW>
		end
		cols=sort(tmp);
		
		
		
		FreqsPlot.delete;
		mainWindow.delete;
	end
	waitfor(mainWindow,'delete');
	
	
	nMar=strrep(markers,'\','');
	f = msgbox(nMar(cols));
	[~,~,cols]=intersect(nMar(cols),MarkerNames);
	waitfor(f);
end

